### PR TITLE
Fixes to m68k

### PR DESCRIPTION
**Pull request by apolkosnik**

### CODE REVIEW

**Comment by sorgelig** [comment]
Why we need m68k? Actually it was pending to be completely removed. TG68K already integrates all changes.
Isn't?

**Comment by apolkosnik** [comment]
Since it was still here, I've ported some fixes. Having options is nice.

**Comment by apolkosnik** [comment]
It would be good to leave it for experimenting, I've heard that somebody was going to implement 32-bit bus on this one, but it's all up to you.

**Comment by sorgelig** [comment]
There is nothing preventing to implement 32bit bus on TG68K. It's better not to spread the work among parallel cores doing basically the same. And knowing that "someone", it won't happen in coming years ;)

**Pull request closed without merging**
